- create: ["~/tmp"]
- link:
    "~/.local/bin/battery-cron": cronjobs/batterystate.sh
    "~/tmp/batteryinfo": cronjobs/batteryinfo
- shell:
    - "echo 'add cronjob battery-cron'>> ~/.to_install"
    - "echo 'upower' >> ~/.to_install"
