resolver: lts-16.2

packages:
- extra-git
- xmonad-git
- xmonad-contrib-git
- xmonad-extras-git
extra-deps: 
- Cabal-3.2.0.0
- text-1.2.4.0
- binary-0.8.8.0
- deepseq-1.4.4.0
- hint-0.9.0.3
- ghc-boot-8.8.3
- time-1.9.3
- netlink-1.1.1.0
- async-2.2.2
- bytestring-0.10.10.0
- containers-0.6.2.1
- directory-1.3.6.1
- extensible-exceptions-0.1.1.4
- filepath-1.4.2.1
- mtl-2.2.2
- old-locale-1.0.0.7
- parsec-3.1.14.0
- parsec-numbers-0.1.0
- process-1.6.10.0
- regex-compat-0.95.2.0
- array-0.5.4.0
- regex-base-0.94.0.0
- regex-posix-0.96.0.0
- stm-2.5.0.0
- transformers-0.5.6.2
- unix-2.7.2.2
- utf8-string-1.0.1.1
- X11-xft-0.3.1
- hinotify-0.4
- libmpd-0.9.1.0
- http-conduit-2.3.7.3
- http-types-0.12.3
- dbus-1.2.7
- dbus-hslogger-0.1.0.1
- gi-dbusmenu-0.4.1
- gi-dbusmenugtk3-0.4.1
- gi-gdk-3.0.15
- gi-gdkpixbuf-2.0.18
- gi-gdkx11-3.0.2
- gi-gio-2.0.16
- gi-gtk-3.0.21
- gi-gtk-hs-0.3.6.1
- gi-pango-1.0.16
- gi-xlib-2.0.2
- gi-glib-2.0.17
- gio-0.13.4.1
- gtk-sni-tray-0.1.6.0
- gtk-strut-0.1.2.1
- haskell-gi-0.21.2
- haskell-gi-base-0.21.1
- libxml-sax-0.7.5
- rate-limit-1.1.1
- spool-0.1
- status-notifier-item-0.3.0.1
- time-units-1.0.0
- xml-helpers-1.0.0
# Override default flag values for local packages and extra-deps
flags:  {}
#  xmobar:
#    with_weather: true
#    with_utf8: true
#    with_xft: true
#    with_inotify: true
#    with_mpd: true
#
# Extra package databases containing global packages
# extra-package-dbs: []

# Control whether we use the GHC we find on the path
# system-ghc: true
#
# Require a specific version of stack, using version ranges
# require-stack-version: -any # Default
# require-stack-version: ">=2.3"
#
# Override the architecture used by stack, especially useful on Windows
# arch: i386
# arch: x86_64
#
# Extra directories used by stack for building
extra-include-dirs: ['lib']
extra-lib-dirs: ['lib']
#
# Allow a newer minor version of GHC than the snapshot specifies
# compiler-check: newer-minor
