#!/bin/sh

# This is the example configuration file for river.
#
# If you wish to edit this, you will probably want to copy it to
# $XDG_CONFIG_HOME/river/init or $HOME/.config/river/init first.
#
# See the river(1), riverctl(1), and rivertile(1) man pages for complete
# documentation.

# Note: the "Super" modifier is also known as Logo, GUI, Windows, Mod4, etc.
riverctl map normal Mod4+Shift Q exit
riverctl map normal Mod4 E spawn "emacsclient -c -a emacs"
riverctl map normal Mod4 Return spawn "foot -e bash -c tmux"
riverctl map normal Mod4 Space spawn "firefox-wayland"
riverctl map normal Mod4 D spawn "wofi --show run"
riverctl map normal Mod4 Escape spawn "makoctl dismiss"
riverctl map normal Mod4 F toggle-fullscreen
riverctl map normal Mod4 W close


riverctl map normal Mod4 J focus-view next
riverctl map normal Mod4 K focus-view previous
riverctl map normal Mod4+Shift J swap next
riverctl map normal Mod4+Shift K swap previous
riverctl map normal Mod4+Shift Return zoom

riverctl map normal Mod4 Space toggle-float

riverctl map normal Mod4+Mod1         H move left  100
riverctl map normal Mod4+Mod1         J move down  100
riverctl map normal Mod4+Mod1         K move up    100
riverctl map normal Mod4+Mod1         L move right 100
riverctl map normal Mod4+Mod1+Control H snap left
riverctl map normal Mod4+Mod1+Control J snap down
riverctl map normal Mod4+Mod1+Control K snap up
riverctl map normal Mod4+Mod1+Control L snap right
riverctl map normal Mod4+Mod1+Shift   H resize horizontal -100
riverctl map normal Mod4+Mod1+Shift   J resize vertical    100
riverctl map normal Mod4+Mod1+Shift   K resize vertical   -100
riverctl map normal Mod4+Mod1+Shift   L resize horizontal  100

riverctl float-filter-add app-id float

riverctl spawn rivertile
riverctl default-layout rivertile
riverctl spawn "emacs --daemon"
riverctl spawn "xset r rate 300 50"
riverctl spawn "yambar"
riverctl spawn "nextcloud"
riverctl spawn "flameshot"
riverctl spawn "mako"
riverctl spawn "nm-applet"

riverctl map normal XF86AudioRaiseVolume spawn "$HOME/.local/bin/soundctl.sh up"
riverctl map normal XF86AudioLowerVolume spawn "$HOME/.local/bin/soundctl.sh down"
riverctl map normal XF86AudioMute spawn "$HOME/.local/bin/soundctl.sh mute"
riverctl map normal XF86BrightnessUp spawn "$HOME/.local/bin/blightctl.sh up"
riverctl map normal XF86BrightnessDown spawn "$HOME/.local/bin/blightctl.sh down"

for i in $(seq 1 9); do
    tagmask=$((1 << ($i -1)))
    riverctl map normal Mod4 $i set-focused-tags $tagmask
    riverctl map normal Mod4+Shift $i set-view-tags $tagmask
    riverctl map normal Mod4+Control $i toggle-focused-tags $tagmask
    riverctl map normal Mod4+Shift+Control $i toggle-view-tags $tagmask
done
all_tags_mask=$(((1 << 32) - 1))
riverctl map normal Mod4       0 set-focused-tags $all_tags_mask
riverctl map normal Mod4+Shift 0 set-view-tags    $all_tags_mask

scratch_tag=$((1 << 20))
riverctl map normal Mod4 P toggle-focused-tags ${scratch_tag}
riverctl map normal Mod4+Shift P set-view-tags ${scratch_tag}
all_but_scratch_tag=$(( ((1 << 32) - 1) ^ "$scratch_tag" ))
riverctl spawn-tagmask ${all_but_scratch_tag}
