#!/bin/bash
bspc config border_width 3

bspc config normal_border_color "#202236"

bspc config active_border_color "#81A9FE"

bspc config focused_border_color "#Bf98FE"

bspc config urgent_border_color "#FE747E"

bspc config presel_feedback_color "#434972"
