hack: &hack Fira Code Nerd Font Mono:pixelsize=16
awesome: &awesome FontAwesome:style=solid:pixelsize=16
bg_river: &bg_river {stack: [{background: {color: 91a9feff}}, {underline: {size: 4, color: c8d3f5ff}}]}
bar:
  height: 30
  location: top
  font: FiraCode Nerd Font Mono:pixelsize=16
  spacing: 5
  margin: 0
  layer: bottom
  foreground: c8d3f5ff
  background: 202236ff

  left:
    - river:
        anchors:
          - base: &river_base
              left-margin: 10
              right-margin: 13 
              default: {string: {text: }}
              tag: id
              values:
                1: {string: {text: , font: *awesome}}
                2: {string: {text: , font: *awesome}}
                3: {string: {text: , font: *awesome}}
                4: {string: {text: , font: *awesome}}
                5: {string: {text: , font: *awesome}}
                20: {string: {text: "scratchpad"}}
        content:
          map:
            on-click:
              left: sh -c "riverctl set-focused-tags $((1 << ({id} - 1)))"
              right: sh -c "riverctl toggle-focused-tags $((1 << ({id} -1)))"
              middle: sh -c "riverctl toggle-view-tags $((1 << ({id} -1)))"
            tag: state
            values:
              urgent:
                map:
                  <<: *river_base
                  deco: {background: {color: fe747eff}}
              focused:
                map:
                  <<: *river_base
                  deco: *bg_river
              visible:
                map:
                  <<: *river_base
              unfocused:
                map:
                  <<: *river_base
              invisible:
                map:
                  <<: *river_base
  right:
    - backlight:
        foreground: fec676ff
        name: intel_backlight
        content: [ string: {text: , font: *awesome,  foreground: fec676ff }, string: {text: "{percent}%"}]

    - battery:
        foreground: fe747eff
        name: BAT1
        poll-interval: 30
        anchors:
          discharging: &discharging
            list:
              items:
                - ramp:
                    tag: capacity
                    items:
                      - string: {text: , font: *awesome}
                      - string: {text: , font: *awesome}
                      - string: {text: , font: *awesome}
                      - string: {text: , font: *awesome}
                      - string: {text: , font: *awesome}
                      - string: {text: , font: *awesome}
                      - string: {text: , font: *awesome}
                      - string: {text: , font: *awesome}
                      - string: {text: , font: *awesome}
                      - string: {text: , font: *awesome}
        content:
          map:
            tag: state
            values:
              unknown:
                <<: *discharging
              discharging:
                <<: *discharging
              charging:
                - string: {text: , foreground: c2e78cff, font: *awesome}
                - ramp:
                    tag: capacity
                    items:
                      - string: {text: , font: *awesome}
                      - string: {text: , font: *awesome}
                      - string: {text: , font: *awesome}
                      - string: {text: , font: *awesome}
                      - string: {text: , font: *awesome}
                      - string: {text: , font: *awesome}
                      - string: {text: , font: *awesome}
                      - string: {text: , font: *awesome}
                      - string: {text: , font: *awesome}
                      - string: {text: , font: *awesome}
                - string: {text: "{capacity}%"}
              full:
                - string: {text: , foreground: c2e78cff, font: *awesome}
                - string: {text: "{capacity}% FULL"}
              not charging:
                - ramp:
                    tag: capacity
                    items:
                      - string: {text:  ,  font: *awesome}
                      - string: {text:  ,  font: *awesome}
                      - string: {text:  ,  font: *awesome}
                      - string: {text:  ,  font: *awesome}
                      - string: {text:  ,  font: *awesome}
                      - string: {text:  ,  font: *awesome}
                      - string: {text:  ,  font: *awesome}
                      - string: {text:  ,  font: *awesome}
                      - string: {text:  ,  font: *awesome}
                      - string: {text:  ,  font: *awesome}
                - string: {text: " {capacity}%"}
