#!/bin/bash
xset s 600 &
xss-lock -- slock &

xset r rate 300 50 &

unclutter &

sxhkd &

~/.config/polybar/launch.sh

feh --bg-fill --randomize ~/Pictures/wallpaper &

nextcloud &

flameshot &

dunst &

nm-applet &

emacs --daemon &

picom &

bspc config top_padding 25

export MONITOR=$(xrandr -q | grep primary | cut -d' ' -f1)
export MONITORS=($(xrandr -q | grep ' connected' | cut -d' ' -f1) )
MONITOR=${MONITOR:-${MONITORS[0]}}

bspc monitor $MONITOR -d {web,term,chat,code,music}
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true

bspc rule -r '*'

bspc rule -a Emacs split_ratio=0.28 state=tiled
bspc rule -a 'Emacs:org*' state=floating
bspc rule -a 'Emacs:scratch' state=floating
bspc rule -a '*:scratch' state=floating sticky=on center=on border=off rectangle=1000x800+0+0

bspc rule -a Pinentry state=floating center=on

bspc rule -a Firefox split_ratio=0.32

bspc rule -a feh state=fullscreen

for file in $XDG_CONFIG_HOME/bspwm/rc.d/*; do
  source "$file"
done
