#!/bin/bash
xset r rate 300 50 &

unclutter &

sxhkd &

~/.config/polybar/launch.sh

feh --bg-fill --randomize ~/Pictures/wallpaper

nextcloud &

flameshot &

dunst &

nm-applet &

bspc config top_padding 25

export MONITOR=$(xrandr -q | grep primary | cut -d' ' -f1)
export MONITORS=($(xrandr -q | grep ' connected' | cut -d' ' -f1) )
MONITOR=${MONITOR:-${MONITORS[0]}}

bspc monitor $MONITOR -d {web,term,chat,code,music}
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true

bspc rule -a Emacs state=tiled
